### ISSUE TITLE
Bug/Error

### ISSUE THREAD

**Issue by Keiu03** [theCrius/project-zomboid-random-zombies-full#12]
**Mod not working and Error is just piling up**

**To Reproduce**
4. etc etc

**Expected behavior**

**Screenshots**

**Specification (please complete the following information):**
- 41.78.16
- Hosted Dedicated Server
- SandboxVars block for the mod

**`Callframe at: error
function: ValidateConfiguration -- file: rzf_utilities.lua line # 63 | MOD: Random Zombies - Day and Night
function: LoadConfiguration -- file: rzf_server.lua line # 74 | MOD: Random Zombies - Day and Night
se.krka.kahlua.vm.KahluaException: [RZF] Crawler, Shambler, FastShambler and Sprinter for the Night Settings do not add up to 100
    at se.krka.kahlua.stdlib.BaseLib.error(BaseLib.java:292)
    at se.krka.kahlua.stdlib.BaseLib.call(BaseLib.java:120)
    at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
    at zombie.gameStates.IngameState.enter(IngameState.java:737)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:145)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`**

**Comment by theCrius** [comment]
Not a bug.

Error explain what is wrong.

> [RZF] Crawler, Shambler, FastShambler and Sprinter for the Night Settings do not add up to 100

**Comment by Keiu03** [comment]
alright thanks!
